// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Acme.Resource.Data.Migrations
{
	[DbContext(typeof(AcmeResourceDbContext))]
	partial class AcmeResourceDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("ProductVersion", "5.0.4")
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Acme.Resource.Data.Models.Employee", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int")
						.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

					b.Property<string>("Birthdate")
						.HasColumnType("date");

					b.Property<int>("EmployeeTypeId")
						.HasColumnType("int");

					b.Property<string>("FullName")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("IsDeleted")
						.HasColumnType("bit");

					b.Property<string>("TIN")
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("Employee");
				});
#pragma warning restore 612, 618
		}
	}
}
